{"uuid": "eeee5ef1-2dd2-4381-9658-4352507bcb2f", "children": ["e01fb899-46ad-4402-8206-1cb722ba6d8e"], "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "ModuleNotFoundError: No module named 'config'\n", "trace": "  File \"C:\\Users\\pappula.l\\AppData\\Roaming\\Python\\Python310\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\pappula.l\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\pappula.l\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\GIT_Projects\\CAW\\tests\\conftest.py\", line 12, in init_driver\n    from config import TestData\n"}, "start": 1709057030232, "stop": 1709057030240}], "start": 1709057030232, "stop": 1709057031023}